# Generated by Django 3.2.11 on 2022-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=20)),
                ('std_roll_num', models.CharField(max_length=20)),
            ],
        ),
    ]
