# Generated by Django 3.2.11 on 2022-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranserFundsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
